### ISSUE TITLE
Bible Kadosh Israelita Mesiánica (Spanish) and compatibility for Holyrics

### ISSUE THREAD

**Issue by NaxiithoxxD** [Beblia/Holy-Bible-XML-Format#5]
Hello, I don't have very good English, so I will use a translator. What happens is that I want to use the Bibles that you provide for a program called "Holyrics", but when I use them it won't let me. It says the following:

- "bible.bibleimport.BibleImportException: Invalid File: SpanishVBLBible.xml tag not found: "XMLBIBLE".

I know it's not what you do, but could you help me?

And if you can, could you also upload the "Kadosh Israelita Mesiánica" Bible?

Update: I noticed that Holyrics uses "Zefania XML".

**Comment by Beblia** [comment]
Sorry for the late reply. Have you solved the issue?

**Comment by NaxiithoxxD** [comment]
> Perdón por la respuesta tardía. ¿Has resuelto el problema?

No, no pude solucionarlo. Sé que es un tema de la estructura de la Biblia y que esta se puede cambiar para adaptarla a "Zefania XML", pero creo que tendría que hacerse manualmente. No pude hacerlo porque mis conocimientos no son muy buenos. Sin embargo, pude conseguir la Biblia Kadosh, pero con código entre los textos, y aunque pude eliminar todos los códigos, algunas partes quedaron con un doble espacio y desconozco si llegué a borrar algo de la biblia.
