### ISSUE TITLE
Holyrics Bible version 

### ISSUE THREAD

**Issue by Wollf2007** [Beblia/Holy-Bible-XML-Format#6]
How do i import the Bible version  in the app Holyrics?

Thanks for the Help.

**Comment by Beblia** [comment]
I have no idea.

**Comment by lsrocha** [comment]
Holyrics only accepts XML files that follows the ZEF schema:

- https://www.bgfdb.de/zefania/
- https://bgfdb.de/zefaniaxml/bml/

The Bible files needs be converted before importing there.
