### ISSUE TITLE
Ghomala 2002 is mislabeled as Galacian

### ISSUE THREAD

**Issue by moyogo** [Beblia/Holy-Bible-XML-Format#8]
Ghomala 2002 is mislabeled as Galacian2002, Ghomala (ISO 639-3: bbj) is a Bantoid language spoken in Cameroon, Galacian (ISO 639-9: gl, ISO 639-3: glg) is a Romance language spoken in Spain.

**Comment by Beblia** [comment]
Thank you. Fixed.
