### ISSUE TITLE
Missing verses

### ISSUE THREAD

**Issue by joelrb** [Beblia/Holy-Bible-XML-Format#9]
There are some missing verses. Problem with your xml exporter?

For example, in **WarayBible.xml** Genesis Chapter 1 verses 6 and 7 are missing. But are not missing in the website (https://beblia.com/Bible?Language=Waray&Book=1&Chapter=1).

![Screenshot 2024-11-09 221134](https://github.com/user-attachments/assets/cb9a50c7-f520-462d-b586-9481af30ad75)

**Comment by joelrb** [comment]
I've asked ChatGPT to check the XML file and give me the missing verses for **WarayBible.xml**. Looks like you need to check your XML exporter.

Here is a summary of only the books and chapters that contain missing verses:

Genesis
Chapter 1: Missing verses 6, 7
Chapter 6: Missing verses 9, 10, 19, 20
Chapter 7: Missing verses 8, 9
Exodo
Chapter 1: Missing verses 13, 14, 20, 21
Chapter 2: Missing verses 15, 16
Chapter 4: Missing verses 25, 26
Levitico
Chapter 6: Missing verses 4, 5, 16, 17
Chapter 8: Missing verses 20, 21
Chapter 11: Missing verses 4–6, 13–19, 24–30
Mga Bilang
Chapter 1: Missing verses 5–46
Chapter 2: Missing verses 3–31
Chapter 3: Missing verses 12, 13, 17, 18, 19, 20, 40, 41
Deuteronomio
Chapter 1: Missing verses 20, 21
Chapter 4: Missing verses 45, 46
Chapter 14: Missing verses 12–18
Josue
Chapter 2: Missing verses 4–6
Chapter 3: Missing verses 14, 15
Chapter 5: Missing verses 4–6
Mga Hukom
Chapter 1: Missing verses 18, 19, 22, 23
Chapter 13: Missing verses 15, 16, 20, 21
Chapter 14: Missing verses 12, 13
1 Samuel
Chapter 1: Missing verses 9, 10
Chapter 3: Missing verses 6, 7
Chapter 9: Missing verses 9–13
Mateo
Chapter 1: Missing verses 2–16
Chapter 2: Missing verses 9, 10
Chapter 13: Missing verses 31, 32
Lucas
Chapter 1: Missing verses 73, 74
Chapter 17: Missing verse 36
Chapter 18: Missing verses 29, 30
Juan
Chapter 4: Missing verses 7, 8
Chapter 10: Missing verses 14, 15
Chapter 11: Missing verses 28–30

**Comment by Beblia** [comment]
Thank you. Fixed!
